// Mocks generated by Mockito 5.0.15 from annotations
// in streaming_platform/test/features/music_player/domain/use_cases/get_audio_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:streaming_platform/core/error/failure.dart' as _i5;
import 'package:streaming_platform/features/music_player/domain/entities/audio_meta.dart'
    as _i6;
import 'package:streaming_platform/features/music_player/domain/repositories/audio_meta_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [AudioMetaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioMetaRepository extends _i1.Mock
    implements _i3.AudioMetaRepository {
  MockAudioMetaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AudioMeta>> getAudioMeta(String? id) =>
      (super.noSuchMethod(Invocation.method(#getAudioMeta, [id]),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.AudioMeta>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AudioMeta>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AudioMeta>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AudioMeta>>
      getRandomAudioMetaFromGroup(String? groupId) => (super.noSuchMethod(
              Invocation.method(#getRandomAudioMetaFromGroup, [groupId]),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.AudioMeta>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AudioMeta>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AudioMeta>>);
  @override
  String toString() => super.toString();
}
